/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  // tutorialSidebar: [
  //   'intro',
  //   'hello',
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['tutorial-basics/create-a-document'],
  //   },
  // ],
  ['Architecture']: [
    'intro',
    {
      type: 'category',
      label: 'Architecture',
      items: [
        'Architecture/Introduction',
        'Architecture/Without state/Без состояния',
        'Architecture/Единственное хранилище',
        'Architecture/Интерактивные хранилища',
        'Architecture/Реактивные хранилища',
        'Architecture/Реактивные хранилища с EDA',
      ],
    },
  ],
  ['100QuestionsSidebar']: [
    '100 Questions/Intro',
    '100 Questions/Content',
    {
      type: 'category',
      label: '100 Questions',
      items: [
        '100 Questions/Content',
        '100 Questions/Content',
        '100 Questions/Content',
      ],
    },
  ],
  ['Other']: [
    'Other/intro',
    'Other/Which computer to choose for learning programming',
    'Other/Project conventions',
    'Other/Tips for a newbie in IT',
    'Other/What to prepare for an interview'
  ],
};

module.exports = sidebars;
